### ISSUE TITLE
Can not squeeze dim[3], expected a dimension of 1, got 3

### ISSUE THREAD

**Issue by xuying156209** [dmolony3/DRN#3]
Hi， i have some problem when running this repo,
the problem is **tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[3], expected a dimension of 1, got 3**
and this is caused by this line according to the error massage.
**label = tf.squeeze(label, 3)**

The log is shown below.
Thanks so much

> 
Traceback (most recent call last):
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[3], expected a dimension of 1, got 3
         [[{{node Squeeze}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    run()
  File "main.py", line 15, in run
    train(config)
  File "/home/xuying/DRN/drn/train_network.py", line 112, in train
    learning_rate:config.learning_rate, train_network:True})
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[3], expected a dimension of 1, got 3
         [[node Squeeze (defined at /home/xuying/DRN/drn/train_network.py:51) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Squeeze:
 IteratorGetNext (defined at /home/xuying/DRN/drn/train_network.py:34)

Original stack trace for 'Squeeze':
  File "main.py", line 23, in <module>
    run()
  File "main.py", line 15, in run
    train(config)
  File "/home/xuying/DRN/drn/train_network.py", line 51, in train
    label = tf.squeeze(label, 3)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 3162, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9666, in squeeze
    "Squeeze", input=input, squeeze_dims=axis, name=name)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/data/xuying/anaconda3/envs/tf14/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by dmolony3** [comment]
I guess this is to do with the encoding of your png files. I've changed data_reader.py so that it should now read the png as a single channel if you want to clone and try again.
